name = "corn-scheduler"
main = "src/index.ts"
compatibility_date = "2024-10-27"

# Cron triggers for 10 AM IST (4:30 AM UTC) and 6 PM IST (12:30 PM UTC)
[triggers]
crons = ["30 4 * * *", "30 12 * * *"]

# Secrets (set using: wrangler secret put API_ENDPOINT)
# API_ENDPOINT = "your-api-endpoint-url"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
